package com.ctrip.soa.artemis.management.config;

/**
 * Created by fang_j on 10/07/2016.
 */
public interface RestPaths {
    String MANAGEMENT_PATH = "/api/management/";
    String MANAGEMENT_OPERATE_INSTANCE_RELATIVE_PATH = "operate-instance.json";
    String MANAGEMENT_OPERATE_INSTANCE_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_OPERATE_INSTANCE_RELATIVE_PATH;
    String MANAGEMENT_OPERATE_SERVER_RELATIVE_PATH = "operate-server.json";
    String MANAGEMENT_OPERATE_SERVER_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_OPERATE_SERVER_RELATIVE_PATH;
    String MANAGEMENT_INSTANCE_OPERATIONS_RELATIVE_PATH = "instance-operations.json";
    String MANAGEMENT_INSTANCE_OPERATIONS_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_INSTANCE_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_SERVER_OPERATIONS_RELATIVE_PATH = "server-operations.json";
    String MANAGEMENT_SERVER_OPERATIONS_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_SERVER_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_ALL_INSTANCE_OPERATIONS_RELATIVE_PATH = "all-instance-operations.json";
    String MANAGEMENT_ALL_INSTANCE_OPERATIONS_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_ALL_INSTANCE_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_ALL_SERVER_OPERATIONS_RELATIVE_PATH = "all-server-operations.json";
    String MANAGEMENT_ALL_SERVER_OPERATIONS_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_ALL_SERVER_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_INSTANCE_DOWN_RELATIVE_PATH = "instance-down.json";
    String MANAGEMENT_INSTANCE_DOWN_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_INSTANCE_DOWN_RELATIVE_PATH;
    String MANAGEMENT_SERVER_DOWN_RELATIVE_PATH = "server-down.json";
    String MANAGEMENT_SERVER_DOWN_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_SERVER_DOWN_RELATIVE_PATH;
    String MANAGEMENT_SERVICES_RELATIVE_PATH = "services.json";
    String MANAGEMENT_SERVICES_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_SERVICES_RELATIVE_PATH;
    String MANAGEMENT_SERVICE_RELATIVE_PATH = "service.json";
    String MANAGEMENT_SERVICE_FULL_PATH = MANAGEMENT_PATH + MANAGEMENT_SERVICE_RELATIVE_PATH;

    String MANAGEMENT_LOG_PATH = "/api/management/log/";
    String MANAGEMENT_INSTANCE_OPERATION_LOGS_RELATIVE_PATH = "instance-operation-logs.json";
    String MANAGEMENT_INSTANCE_OPERATION_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_INSTANCE_OPERATION_LOGS_RELATIVE_PATH;
    String MANAGEMENT_SERVER_OPERATION_LOGS_RELATIVE_PATH = "server-operation-logs.json";
    String MANAGEMENT_SERVER_OPERATION_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_SERVER_OPERATION_LOGS_RELATIVE_PATH;
    String MANAGEMENT_GROUP_OPERATION_LOGS_RELATIVE_PATH = "group-operation-logs.json";
    String MANAGEMENT_GROUP_OPERATION_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_GROUP_OPERATION_LOGS_RELATIVE_PATH;
    String MANAGEMENT_GROUP_LOGS_RELATIVE_PATH = "group-logs.json";
    String MANAGEMENT_GROUP_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_GROUP_LOGS_RELATIVE_PATH;
    String MANAGEMENT_ROUTE_RULE_LOGS_RELATIVE_PATH = "route-rule-logs.json";
    String MANAGEMENT_ROUTE_RULE_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_ROUTE_RULE_LOGS_RELATIVE_PATH;
    String MANAGEMENT_ROUTE_RULE_GROUP_LOGS_RELATIVE_PATH = "route-rule-group-logs.json";
    String MANAGEMENT_ROUTE_RULE_GROUP_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_ROUTE_RULE_GROUP_LOGS_RELATIVE_PATH;
    String MANAGEMENT_ZONE_OPERATION_LOGS_RELATIVE_PATH = "zone-operation-logs.json";
    String MANAGEMENT_ZONE_OPERATION_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_ZONE_OPERATION_LOGS_RELATIVE_PATH;
    String MANAGEMENT_GROUP_INSTANCE_LOGS_RELATIVE_PATH = "group-instance-logs.json";
    String MANAGEMENT_GROUP_INSTANCE_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_GROUP_INSTANCE_LOGS_RELATIVE_PATH;
    String MANAGEMENT_SERVICE_INSTANCE_LOGS_RELATIVE_PATH = "service-instance-logs.json";
    String MANAGEMENT_SERVICE_INSTANCE_LOGS_FULL_PATH = MANAGEMENT_LOG_PATH + MANAGEMENT_SERVICE_INSTANCE_LOGS_RELATIVE_PATH;

    String MANAGEMENT_GROUP_PATH = "/api/management/group/";

    String MANAGEMENT_INSERT_ROUTE_RULES_RELATIVE_PATH = "insert-route-rules.json";
    String MANAGEMENT_INSERT_ROUTE_RULES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_INSERT_ROUTE_RULES_RELATIVE_PATH;
    String MANAGEMENT_UPDATE_ROUTE_RULES_RELATIVE_PATH = "update-route-rules.json";
    String MANAGEMENT_UPDATE_ROUTE_RULES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_UPDATE_ROUTE_RULES_RELATIVE_PATH;
    String MANAGEMENT_DELETE_ROUTE_RULES_RELATIVE_PATH = "delete-route-rules.json";
    String MANAGEMENT_DELETE_ROUTE_RULE_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_DELETE_ROUTE_RULES_RELATIVE_PATH;
    String MANAGEMENT_GET_ROUTE_RULES_RELATIVE_PATH = "get-route-rules.json";
    String MANAGEMENT_GET_ROUTE_RULES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_ROUTE_RULES_RELATIVE_PATH;
    String MANAGEMENT_GET_ALL_ROUTE_RULES_RELATIVE_PATH = "get-all-route-rules.json";
    String MANAGEMENT_GET_ALL_ROUTE_RULES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_ALL_ROUTE_RULES_RELATIVE_PATH;
    String MANAGEMENT_CREATE_ROUTE_RULE_RELATIVE_PATH = "create-route-rule.json";
    String MANAGEMENT_CREATE_ROUTE_RULE_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_CREATE_ROUTE_RULE_RELATIVE_PATH;

    String MANAGEMENT_INSERT_ROUTE_RULE_GROUPS_RELATIVE_PATH = "insert-route-rule-groups.json";
    String MANAGEMENT_INSERT_ROUTE_RULE_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_INSERT_ROUTE_RULE_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_UPDATE_ROUTE_RULE_GROUPS_RELATIVE_PATH = "update-route-rule-groups.json";
    String MANAGEMENT_UPDATE_ROUTE_RULE_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_UPDATE_ROUTE_RULE_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_RELEASE_ROUTE_RULE_GROUPS_RELATIVE_PATH = "release-route-rule-groups.json";
    String MANAGEMENT_RELEASE_ROUTE_RULE_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_RELEASE_ROUTE_RULE_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_DELETE_ROUTE_RULE_GROUPS_RELATIVE_PATH = "delete-route-rule-groups.json";
    String MANAGEMENT_DELETE_ROUTE_RULE_GROUP_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_DELETE_ROUTE_RULE_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_GET_ALL_ROUTE_RULE_GROUPS_RELATIVE_PATH = "get-all-route-rule-groups.json";
    String MANAGEMENT_GET_ALL_ROUTE_RULE_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_ALL_ROUTE_RULE_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_GET_ROUTE_RULE_GROUPS_RELATIVE_PATH = "get-route-rule-groups.json";
    String MANAGEMENT_GET_ROUTE_RULE_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_ROUTE_RULE_GROUPS_RELATIVE_PATH;

    String MANAGEMENT_INSERT_GROUPS_RELATIVE_PATH = "insert-groups.json";
    String MANAGEMENT_INSERT_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_INSERT_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_UPDATE_GROUPS_RELATIVE_PATH = "update-groups.json";
    String MANAGEMENT_UPDATE_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_UPDATE_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_DELETE_GROUPS_RELATIVE_PATH = "delete-groups.json";
    String MANAGEMENT_DELETE_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_DELETE_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_GET_GROUPS_RELATIVE_PATH = "get-groups.json";
    String MANAGEMENT_GET_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_GROUPS_RELATIVE_PATH;
    String MANAGEMENT_GET_ALL_GROUPS_RELATIVE_PATH = "get-all-groups.json";
    String MANAGEMENT_GET_ALL_GROUPS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_ALL_GROUPS_RELATIVE_PATH;

    String MANAGEMENT_INSERT_GROUP_TAGS_RELATIVE_PATH = "insert-group-tags.json";
    String MANAGEMENT_INSERT_GROUP_TAGS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_INSERT_GROUP_TAGS_RELATIVE_PATH;
    String MANAGEMENT_UPDATE_GROUP_TAGS_RELATIVE_PATH = "update-group-tags.json";
    String MANAGEMENT_UPDATE_GROUP_TAGS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_UPDATE_GROUP_TAGS_RELATIVE_PATH;
    String MANAGEMENT_DELETE_GROUP_TAGS_RELATIVE_PATH = "delete-group-tags.json";
    String MANAGEMENT_DELETE_GROUP_TAGS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_DELETE_GROUP_TAGS_RELATIVE_PATH;
    String MANAGEMENT_GET_GROUP_TAGS_RELATIVE_PATH = "get-group-tags.json";
    String MANAGEMENT_GET_GROUP_TAGS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_GROUP_TAGS_RELATIVE_PATH;
    String MANAGEMENT_GET_ALL_GROUP_TAGS_RELATIVE_PATH = "get-all-group-tags.json";
    String MANAGEMENT_GET_ALL_GROUP_TAGS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_ALL_GROUP_TAGS_RELATIVE_PATH;

    String MANAGEMENT_OPERATE_GROUP_OPERATIONS_RELATIVE_PATH = "operate-group-operations.json";
    String MANAGEMENT_OPERATE_GROUP_OPERATIONS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_OPERATE_GROUP_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_OPERATE_GROUP_OPERATION_RELATIVE_PATH = "operate-group-operation.json";
    String MANAGEMENT_OPERATE_GROUP_OPERATION_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_OPERATE_GROUP_OPERATION_RELATIVE_PATH;
    String MANAGEMENT_GET_ALL_GROUP_OPERATIONS_RELATIVE_PATH = "get-all-group-operations.json";
    String MANAGEMENT_GET_ALL_GROUP_OPERATIONS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_ALL_GROUP_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_GET_GROUP_OPERATIONS_RELATIVE_PATH = "get-group-operations.json";
    String MANAGEMENT_GET_GROUP_OPERATIONS_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_GROUP_OPERATIONS_RELATIVE_PATH;

    String MANAGEMENT_INSERT_GROUP_INSTANCES_RELATIVE_PATH = "insert-group-instances.json";
    String MANAGEMENT_INSERT_GROUP_INSTANCES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_INSERT_GROUP_INSTANCES_RELATIVE_PATH;
    String MANAGEMENT_DELETE_GROUP_INSTANCES_RELATIVE_PATH = "delete-group-instances.json";
    String MANAGEMENT_DELETE_GROUP_INSTANCES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_DELETE_GROUP_INSTANCES_RELATIVE_PATH;
    String MANAGEMENT_GET_GROUP_INSTANCES_RELATIVE_PATH = "get-group-instances.json";
    String MANAGEMENT_GET_GROUP_INSTANCES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_GROUP_INSTANCES_RELATIVE_PATH;

    String MANAGEMENT_INSERT_SERVICE_INSTANCES_RELATIVE_PATH = "insert-service-instances.json";
    String MANAGEMENT_INSERT_SERVICE_INSTANCES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_INSERT_SERVICE_INSTANCES_RELATIVE_PATH;
    String MANAGEMENT_DELETE_SERVICE_INSTANCES_RELATIVE_PATH = "delete-service-instances.json";
    String MANAGEMENT_DELETE_SERVICE_INSTANCES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_DELETE_SERVICE_INSTANCES_RELATIVE_PATH;
    String MANAGEMENT_GET_SERVICE_INSTANCES_RELATIVE_PATH = "get-service-instances.json";
    String MANAGEMENT_GET_SERVICE_INSTANCES_FULL_PATH = MANAGEMENT_GROUP_PATH + MANAGEMENT_GET_SERVICE_INSTANCES_RELATIVE_PATH;

    String MANAGEMENT_ZONE_PATH = "/api/management/zone/";

    String MANAGEMENT_OPERATE_ZONE_OPERATIONS_RELATIVE_PATH = "operate-zone-operations.json";
    String MANAGEMENT_OPERATE_ZONE_OPERATIONS_FULL_PATH = MANAGEMENT_ZONE_PATH + MANAGEMENT_OPERATE_ZONE_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_GET_ALL_ZONE_OPERATIONS_RELATIVE_PATH = "get-all-zone-operations.json";
    String MANAGEMENT_GET_ALL_ZONE_OPERATIONS_FULL_PATH = MANAGEMENT_ZONE_PATH + MANAGEMENT_GET_ALL_ZONE_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_GET_ZONE_OPERATIONS_RELATIVE_PATH = "get-zone-operations.json";
    String MANAGEMENT_GET_ZONE_OPERATIONS_FULL_PATH = MANAGEMENT_ZONE_PATH + MANAGEMENT_GET_ZONE_OPERATIONS_RELATIVE_PATH;
    String MANAGEMENT_GET_ZONE_OPERATIONS_LIST_RELATIVE_PATH = "get-zone-operations-list.json";
    String MANAGEMENT_GET_ZONE_OPERATIONS_LIST_FULL_PATH = MANAGEMENT_ZONE_PATH + MANAGEMENT_GET_ZONE_OPERATIONS_LIST_RELATIVE_PATH;
    String MANAGEMENT_IS_ZONE_DOWN_RELATIVE_PATH = "is-zone-down.json";
    String MANAGEMENT_IS_ZONE_DOWN_FULL_PATH = MANAGEMENT_ZONE_PATH + MANAGEMENT_IS_ZONE_DOWN_RELATIVE_PATH;

    String MANAGEMENT_CANARY_PATH = "/api/management/canary/";
    String MANAGEMENT_UPDATE_CANARY_IPS_RELATIVE_PATH = "update-canary-ips.json";
    String MANAGEMENT_UPDATE_CANARY_IPS_FULL_PATH = MANAGEMENT_CANARY_PATH + MANAGEMENT_UPDATE_CANARY_IPS_RELATIVE_PATH;
}
